# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[('libs/opus.dll', '.')],
    datas=[('app.ico', '.')],
    hiddenimports=[
        'customtkinter',
        'pyaudio',
        'numpy',
        'yaml',
        'PIL.Image',
        'PIL.ImageTk',
        'requests',
        'keyboard',
        # 内部模块（确保 PyInstaller 能发现）
        'core',
        'core.protocol',
        'core.codec',
        'core.packet_factory',
        'core.packet_parser',
        'config',
        'config.settings',
        'network',
        'network.udp_client',
        'network.connection_manager',
        'network.api_client',
        'services',
        'services.talk_service',
        'services.room_service',
        'services.location_service',
        'services.mdc1200',
        'services.tail_tone_service',
        'audio',
        'audio.audio_handler',
        'audio.audio_manager',
        'ptt',
        'ptt.hotkey',
        'ui',
        'ui.theme',
        'ui.app',
        'ui.components',
        'ui.components.status_bar',
        'ui.components.ptt_button',
        'ui.components.chat_panel',
        'ui.components.room_selector',
        'ui.components.audio_panel',
        'ui.components.config_dialog',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter.test',
        'unittest',
        'pydoc',
        'distutils',
        'setuptools',
        'pip',
        'lib2to3',
        'test',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='78HAM',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app.ico',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='78HAM',
)
